import { readFile, writeFile, copyFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);
const ace = new URL('node_modules/ace-builds/', root);
const version = JSON.parse(await readFile(new URL('package.json', ace), 'utf8')).version;
if (version !== '1.44.0') throw new Error(`Expected Ace 1.44.0, got ${version}`);
const vendor = (await readFile(new URL('src-noconflict/keybinding-vim.js', ace), 'utf8'))
  .replaceAll('ace/keyboard/vim', 'ace/keyboard/cs128-vim');
const source = await readFile(new URL('src/content.js', root), 'utf8');
// A function wrapper delays registration until the site's own Ace is ready.
// No eval, dynamic scripts, second Ace runtime, or runtime network requests.
const bundle = `// Generated by npm run build. Ace ${version}; see LICENSE-ace.txt and THIRD-PARTY-NOTICES.txt.\n(() => {\nfunction registerBundledVim(ace) {\n${vendor}\n}\n${source}\n})();\n`;
await writeFile(new URL('extension/content.js', root), bundle);
await copyFile(new URL('LICENSE', ace), new URL('extension/LICENSE-ace.txt', root));
console.log(`Built ${fileURLToPath(new URL('extension/', root))}`);
